### PR TITLE
Transformers for auth_oidc into OS741

### PR DESCRIPTION
**Pull request by ScottVerbeek**

### CODE REVIEW

**Comment by rhell4** [comment]
Hey @ScottVerbeek these are the missing events I found for auth_oidc;

- action_failed
- user_connected
- user_created
- user_disconnected

**Comment by ScottVerbeek** [comment]
> We can exclude
>  - action_failed
>  - user_connected
>  - user_created
>  - user_disconnected
> 
> On the basis that action_failed - we won’t know who it is.
>
>  user_created is an administrative function.
>
>  user_connected/disconnected is related to OIDC interaction, not explicit student student activity.

Hi @rhell4 , thanks for reviewing. Alison confirmed that these event don't need to be included. See: https://cquniversity.atlassian.net/browse/OS-828?focusedCommentId=20834

**Comment by ScottVerbeek** [comment]
James Jephcott had requested last commit. Renaming the display values for verbs to a generic value.

**Review by rhell4 — APPROVED** [review]
Reviewed, approving for merge.

**Pull request merged**
