### PR TITLE
Transformers for mod_surveypro into OS741

### PR DESCRIPTION
**Pull request by ScottVerbeek**

### CODE REVIEW

**Comment by rhell4** [comment]
Hey @ScottVerbeek I can see the following events don't have transformers;

- all_submissions_exported
- item_hidden
- item_shown
- mastertemplate_saved
- submissions_imported
- usertemplate_applied
- usertemplate_deleted
- usertemplate_imported

Is this intended?

**Comment by ScottVerbeek** [comment]
> - all_submissions_exported
> - item_hidden
> - item_shown
> - mastertemplate_saved
> - submissions_imported
> - usertemplate_applied
> - usertemplate_deleted
> - usertemplate_imported
>
>All administrative.  Don’t implement.


Hi @rhell4 , thanks for  reviewing. Alison has confirmed that these events don't need to be included. See https://cquniversity.atlassian.net/browse/OS-837?focusedCommentId=20835

**Comment by ScottVerbeek** [comment]
James Jephcott had requested last commit. Renaming the display values for verbs to a generic value.

**Review by rhell4 — APPROVED** [review]
Reviewed, approving for merge.

**Pull request merged**
