### PR TITLE
Transformers for mod_oublog into OS741

### PR DESCRIPTION
**Pull request by ScottVerbeek**

### CODE REVIEW

**Comment by rhell4** [comment]
Hey @ScottVerbeek there's one missing event for this one, save_failed

**Comment by ScottVerbeek** [comment]
> save_failed means nothing happened.
>
> Don’t log.

Hi @rhell4 , thanks for reviewing Alison has confirmed that this event does not need to be included. See https://cquniversity.atlassian.net/browse/OS-839?focusedCommentId=20836

**Comment by ScottVerbeek** [comment]
James Jephcott had requested last commit. Renaming the display values for verbs to a generic value.

**Review by rhell4 — APPROVED** [review]
Reviewed, approving for merge.

**Pull request merged**
