### PR TITLE
GVM Logstore plugin update 2

### LINKED ISSUE #2: Add configuration options for hashing of email address and inclusion of name
We've currently hard-coded the email address to always be hashed when recording logs. This should be behind a configuration option. 

I've also noticed that we've removed the logging of the user's name as part of the customisations. This should be behind a configuration option as well.

- [ ] Configuration option for hashing email address
- [ ] Configuration option for including name

### PR DESCRIPTION
**Pull request by gvm-dev**
**Description**
SCORM scaled score adjustment; added config settings for email hashing, name inclusion

**PR Type**
1 fix 1 enhancement

### CODE REVIEW

**Comment by JoelDSmith** [comment]
Looks like a bump to the plugin version is missing...

**Comment by JoelDSmith** [comment]
I'm not 100% sure why the old commits are showing for this PR as well, but rebasing your changes on top of our `master` might resolve it (I do see that your fork is 3 commits behind).

**Comment by gvm-dev** [comment]
Hi Joel - I can't do a rebase from within the web interface. 

I can see that from the 3 commits in question, 2 concern files that the pull request doesn't touch and the third was the approval of the previous pull request. I don't think there would be a problem with accepting this one.

There was one conflict in the src/transformer/utils/get_user.php file but I resolved this.

**Review by JoelDSmith — APPROVED** [review]
These changes look reasonable to me.

**Pull request merged**
